NORNS_VERSION_MAJOR = 0
NORNS_VERSION_MINOR = 0
NORNS_VERSION_PATCH = 0

$(eval NORNS_VERSION_HASH = \"$(shell git show HEAD | grep commit | sed 's@commit @@')\")

VERSION = -DVERSION_MAJOR=$(NORNS_VERSION_MAJOR) \
	-D VERSION_MINOR=$(NORNS_VERSION_MINOR) \
	-D VERSION_PATCH=$(NORNS_VERSION_PATCH) \
	-D VERSION_HASH=$(NORNS_VERSION_HASH)
