
local k = {}

k[false] = {}
k[true] = {}

k[false].SPACE = ' '
k[false].Q = ';'
k[false]['0'] = '0'
k[false]['1'] = '1'
k[false]['2'] = '2'
k[false]['3'] = '3'
k[false]['4'] = '4'
k[false]['5'] = '5'
k[false]['6'] = '6'
k[false]['7'] = '7'
k[false]['8'] = '8'
k[false]['9'] = '9'
k[false].GRAVE = '`'
k[false].MINUS = '-'
k[false].EQUAL = '='
k[false].LEFTBRACE = '['
k[false].RIGHTBRACE = ']'
k[false].BACKSLASH = '\\'
k[false].APOSTROPHE = '\''
k[false].COMMA = ','
k[false].DOT = '.'
k[false].SLASH = '/'
k[true].SPACE = ' '
k[true].A = 'A'
k[true].B = 'B'
k[true].C = 'C'
k[true].D = 'D'
k[true].E = 'E'
k[true].F = 'F'
k[true].G = 'G'
k[true].H = 'H'
k[true].I = 'I'
k[true].J = 'J'
k[true].K = 'K'
k[true].L = 'L'
k[true].M = 'M'
k[true].N = 'N'
k[true].O = 'O'
k[true].P = 'P'
k[true].Q = ':'
k[true].R = 'R'
k[true].S = 'S'
k[true].T = 'T'
k[true].U = 'U'
k[true].V = 'V'
k[true].X = 'X'
k[true].Y = 'Y'
k[true].Z = 'Z'
k[true]['0'] = ')'
k[true]['1'] = '!'
k[true]['2'] = '@'
k[true]['3'] = '#'
k[true]['4'] = '$'
k[true]['5'] = '%'
k[true]['6'] = '^'
k[true]['7'] = '&'
k[true]['8'] = '*'
k[true]['9'] = '('
k[true].GRAVE = '~'
k[true].MINUS = '_'
k[true].EQUAL = '+'
k[true].LEFTBRACE = '{'
k[true].RIGHTBRACE = '}'
k[true].BACKSLASH = '|'
k[true].APOSTROPHE = '"'
k[true].COMMA = '<'
k[true].DOT = '>'
k[true].SLASH = '?'


return k
