local ControlSpec = require 'controlspec'
local Formatters = require 'jah/formatters'
local Shift = {}

-- Autogenerated using Engine_Shift.generateLuaEngineModuleSpecsSection

local specs = {}

specs.pitch_ratio = ControlSpec.new(0, 4, "linear", 0, 1, "")
specs.pitch_dispersion = ControlSpec.new(0, 4, "linear", 0, 0, "")
specs.time_dispersion = ControlSpec.new(0, 1, "linear", 0, 0, "")
specs.freqshift_freq = ControlSpec.new(-2000, 2000, "linear", 0, 0, "Hz")

Shift.specs = specs

local function bind(paramname, id, formatter)
  params:add_control(id, paramname, specs[id], formatter)
  params:set_action(id, engine[id])
end

function Shift.add_params()
  bind("pitch ratio", "pitch_ratio", Formatters.percentage)
  bind("pitch dispersion", "pitch_dispersion", Formatters.percentage)
  bind("time dispersion", "time_dispersion", Formatters.percentage)
  bind("freqshift freq", "freqshift_freq")
end

return Shift
