top = '..'

def build_ugen(bld, target, source):
    ugen = bld.shlib(features='c cxx',
        source=source,
        target=target,
        use=['SUPERCOLLIDER'],
        install_path='${PREFIX}/lib/SuperCollider/plugins',
        cflags=['-O3', '-Wall'])

    if bld.env.DEST_OS == 'darwin':
        ugen.env.cxxshlib_PATTERN = '%s.scx'
    else:
        ugen.env.cxxshlib_PATTERN = '%s.so'

def build(bld):
    build_ugen(bld, 'BufWrPre', 'ugens/BufWrPre/BufWrPre.cpp')
    build_ugen(bld, 'SoftCutHead', [
        'ugens/SoftCutHead/SoftCutHead.cpp',
        'ugens/SoftCutHead/SoftCutHeadLogic.cpp',
    ])
    build_ugen(bld, 'FaustZitaRev', 'ugens/FaustZitaRev/FaustZitaRev.cpp')
    build_ugen(bld, 'FaustCompressor', 'ugens/FaustCompressor/FaustCompressor.cpp')
    build_ugen(bld, 'TrigPhasor', 'ugens/TrigPhasor/TrigPhasor.cpp')
