top = '..'

def build(bld):
    ugen = bld.shlib(features='c cxx',
        source='ugens/BufWrPre/BufWrPre.cpp',
        target='BufWrPre',
        use=['SUPERCOLLIDER'],
        install_path='${PREFIX}/lib/SuperCollider/plugins')

    ugen.env.cxxshlib_PATTERN = '%s.so'

    ugen = bld.shlib(features='c cxx',
        source=[
            'ugens/SoftCutHead/SoftCutHead.cpp',
            'ugens/SoftCutHead/SoftCutHeadLogic.cpp',
        ],
        target='SoftCutHead',
        use=['SUPERCOLLIDER'],
        install_path='${PREFIX}/lib/SuperCollider/plugins')

    ugen.env.cxxshlib_PATTERN = '%s.so'
