--- AUTOGENERATED by crow utility
-- github.com/monome/crow/util/ii_norns_events.lua

-- run from crow project root directory:
--      lua util/ii_norns_events.lua lua/ii/ <norns_path>/lua/core/crow/ii_events.lua

local events = {}

events.ansible = function(i,v) crow.ii.ansibleevent(i,v) end
events.crow = function(i,v) crow.ii.crowevent(i,v) end
events.faders = function(i,v) crow.ii.fadersevent(i,v) end
events.kria = function(i,v) crow.ii.kriaevent(i,v) end
events.levels = function(i,v) crow.ii.levelsevent(i,v) end
events.meadowphysics = function(i,v) crow.ii.meadowphysicsevent(i,v) end
events.txi = function(i,v) crow.ii.txievent(i,v) end
events.wslash = function(i,v) crow.ii.wslashevent(i,v) end

return events