name: release

on:
  pull_request: # delete this after the workflow has been merged to main
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Date code of release'
        type: string
        required: true
        default: '999999'
      maiden_tag:
        description: 'Maiden release tag to include'
        type: string
        required: true
        default: 'v1.1.5'

jobs:
  create-release-archive:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - id: build
      uses: ./.github/actions/build-norns
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Pack release archive
      run: |
        shopt -s extglob dotglob
        mkdir -p ${RELEASE_NAME}/norns
        mkdir -p ${RELEASE_NAME}/config
        mkdir -p ${RELEASE_NAME}/lib
        mkdir -p ${RELEASE_NAME}/package
        cp update/update.sh ${RELEASE_NAME}
        cp update/changelog.txt ${RELEASE_NAME}
        cp update/version.txt ${RELEASE_NAME}
        cp -r !(${RELEASE_NAME}) ${RELEASE_NAME}/norns
        cp -r image/config/* ${RELEASE_NAME}/config
        curl -LO https://github.com/monome/maiden/releases/download/${MAIDEN_TAG}/maiden-${MAIDEN_TAG}.tgz
        tar xzvf maiden-${MAIDEN_TAG}.tgz
        mv maiden ${RELEASE_NAME}
        rm maiden-${MAIDEN_TAG}.tgz
        tar czvf norns${RELEASE_NAME}.tgz ${RELEASE_NAME}/
        sha256sum norns${RELEASE_NAME}.tgz > norns${RELEASE_NAME}.sha256
      env:
        RELEASE_NAME: ${{ inputs.release_name || '999999' }}
        MAIDEN_TAG: ${{ inputs.maiden_tag || 'v1.1.5' }}
    - name: 'Upload release archive'
      uses: actions/upload-artifact@v7
      with:
        path: norns${{ inputs.release_name || '999999' }}.tgz
        archive: false
    - name: 'Upload release checksum'
      uses: actions/upload-artifact@v7
      with:
        path: norns${{ inputs.release_name || '999999' }}.sha256
        archive: false
